package net.stuarthendren.jung.graph;

import java.util.Collection;
import java.util.HashSet;

import edu.uci.ics.jung.graph.Graph;

/**
 * An induced graph is the subgraph generated by a subset of vertices.
 * 
 * For the graph G(V, E) the induced graph of W &lt; V is the subgraph G(W, F) where F &lt; E and e in E is in F if and only
 * if all vertices incident on e in G(V,E) are contained in W
 * 
 * 
 * @author Stuart Hendren
 * 
 * @param <V>
 * @param <E>
 */
public class BackedInducedGraph<V, E> extends AbstractInducedGraph<V, E> {

	/**
	 * Create the subgraph of <code>graph</code> induces by the <code>vertices</code> This implementation is backed by
	 * the input collection and changes in the original collection will be reflected by changes in the induced graph
	 * 
	 * @param graph
	 * @param vertices
	 */
	public BackedInducedGraph(Graph<V, E> graph, Collection<V> vertices) {
		super(graph, vertices);
	}

	@Override
	public Collection<E> getEdges() {
		Collection<E> edges = new HashSet<E>();
		for (V v : vertices) {
			for (E e : graph.getIncidentEdges(v)) {
				if (vertices.contains(graph.getOpposite(v, e))) {
					edges.add(e);
				}
			}
		}
		return edges;
	}

}
